# Generated by Django 5.1.2 on 2024-10-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
