# Generated by Django 5.0.6 on 2024-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0002_categoria_enabled_producto_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargo_nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('encargo_cantidad_producto', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('encargo_fecha', models.DateField(verbose_name='Día en que lo necesita')),
                ('encargo_comentario_extra', models.TextField(blank=True, verbose_name='Comentarios extra')),
            ],
        ),
    ]
