# Generated by Django 5.1.2 on 2024-11-30 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0002_categoria_enabled_producto_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioProducto', models.IntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fechaPago', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marieweb.producto')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
