# Generated by Django 5.0.6 on 2024-12-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0003_encargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='encargo_estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('en_camino', 'En Camino'), ('listo_para_recoger', 'Listo para Recoger')], default='en_proceso', max_length=20),
        ),
    ]
