# Generated by Django 5.1.2 on 2024-11-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0003_deuda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='precioProducto',
            new_name='monto',
        ),
    ]
