# Generated by Django 5.1.2 on 2024-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0004_rename_precioproducto_deuda_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deuda',
            name='producto',
        ),
        migrations.AddField(
            model_name='deuda',
            name='productos',
            field=models.ManyToManyField(to='marieweb.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_comprada',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
