# Generated by Django 5.1.2 on 2024-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0005_remove_deuda_producto_deuda_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deuda',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='monto',
        ),
        migrations.AddField(
            model_name='deuda',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
