# Generated by Django 5.1.2 on 2024-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0006_remove_deuda_cantidad_remove_deuda_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
