# Generated by Django 5.1.2 on 2024-12-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0007_deuda_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='monto',
            new_name='monto_total',
        ),
    ]
