# Generated by Django 5.1.2 on 2024-12-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0008_rename_monto_deuda_monto_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad_comprada',
            new_name='cantidad_seleccionada',
        ),
    ]
