# Generated by Django 5.1.2 on 2024-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0009_rename_cantidad_comprada_producto_cantidad_seleccionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_seleccionada',
        ),
        migrations.AddField(
            model_name='deuda',
            name='cantidad_productos',
            field=models.JSONField(default=dict),
        ),
    ]
