# Generated by Django 5.1.2 on 2024-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0010_remove_producto_cantidad_seleccionada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
