# Generated by Django 5.1.2 on 2024-12-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marieweb', '0004_encargo_encargo_estado'),
        ('marieweb', '0011_deuda_fecha_limite'),
    ]

    operations = [
    ]
